apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rw0zoacy9-python
  janus-idp.io/tekton: rw0zoacy9-python
  backstage.io/kubernetes-id: rw0zoacy9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rw0zoacy9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
